### ISSUE TITLE
How to customize cursor's position

### ISSUE THREAD

**Issue by afc163** [wesleytodd/prompt-improved#1]
![](https://i.alipayobjects.com/i/localhost/png/201404/2TYrJNrCrV.png)

How to customize my cursor at the left one？

**Comment by wesleytodd** [comment]
To be honest, I would recommend you use https://github.com/SBoudrias/Inquirer.js.

This lib has a few problems and was created back when I didn't know about inquirer.  Also, inquirer is pretty great.

**Comment by afc163** [comment]
Thx for reply, it is helpful.
